name = "JLFzf"
uuid = "1019f520-868f-41f5-a6de-eb00f4b6a39c"
authors = ["Moelf <proton@jling.dev> and contributors"]
version = "0.1.5"

[deps]
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
fzf_jll = "214eeab7-80f7-51ab-84ad-2988db7cef09"

[compat]
Pipe = "1.3.0"
fzf_jll = "0.29,0.30"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
